### ISSUE TITLE
状态样式增加 html 前缀的缺陷

### ISSUE THREAD

**Issue by nimoc** [fast-flow/trees#1]
某些情况下再状态样式前增加 html 反而会让权重恶性循环变得越来越高，不得不采用注释和声明顺序的方式解决

**应该考虑一个更完善的解决方法，状态样式也分级别？ 考虑好以后修改 select.react loading.react 的样式**
```css
html .r-loading--container {
    .r-loading-loading {
        z-index: 100;
        position: absolute;
        left:50%;
        top:50%;
        margin-left: -10px;
        margin-top: -10px;
        /*
            IE8+ use transform
            transform:translateX(-50%);
            transform:translateY(-50%);
        */
    }
}
// Must cover .r-loading--container
html .r-loading--customPostion {
    .r-loading-loading {
        left:auto;
        top:auto;
        margin-top: 0;
        margin-left: 0
    }
}
```
