### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by nimoc** [fast-flow/trees#3]
取消模块的 html .m-list--on {}

## table

````html
<table class="m-list" >
    <thead class="m-list-thead">
        <tr class="m-list-thead-tr" >
            <th class="m-list-thead-tr-th" >
                head
            </th>
        </tr>
    </thead>
    <tbody class="m-list-tbody" >
        <tr class="m-list-tr" >
            <td class="m-list-td" >
                <div class="m-list-td-table">

                </div>
            </td>
        </tr>
    </tbody>
</table>
````

## 多个模块样式覆盖

````html
<div class="m-form">
    <div class="m-form-submit"></div>
</div>
````

````less
.m-form-submit {
    .m-btn();
    .m-btn--primary();
}
````

##  模块的组合

一个 HTML tag 的 class 不允许出现2个不同模块，但可以嵌套。

**bad**
````html
<div class="m-form m-list">
        <div class="m-list-item m-form-item">
            <input type="text" class="m-form-item-input" >
        </div>
</div>
````

**good**
````html
<div class="m-form">
    <div class="m-list">
        <input type="text" class="m-form-item-input" >
    </div>
</div>
````

## free

.m-item-f-import {

}

## 页面样式覆盖

````html
<div class="m-list">
    <div class="m-list-item forgetPassword-m-list-item-v--boss">abc</div>
    <div class="m-list-item">123</div>
    <div class="m-list-item">I II III</div>
</div>

<div class="list">

</div>
````

````less
// default
// forgetPassword {page name}
html .forgetPassword-m-list-item-v--boss {
    color:red;
}
// css module
html .list-item--boss {
    color:red;
}
````

## 样式 extend 顺序

** bad **
```less
.m-form-submit {
    color:red;
    .m-btn();
    .m-btn--primary();
}
```

** good **
```less
.m-form-submit {
    .m-btn();
    .m-btn--primary();
    color:red;
}
```

## tab

.m-tab--themes-simple>.m-tab-hd {
    
}
